### ISSUE TITLE
Version check returns "Error Code: 7"

### ISSUE THREAD

**Issue by Scriptbash** [CSHS-CWRA/RavenHydroFramework#25] opened 2024-01-17 15:44 UTC
### Setup Information

- Raven version: 3.8
- Operating System: Fedora Linux 39 (Workstation Edition), Flatpak

### Description

When running "./Raven.exe -v" or "flatpak run ca.uwaterloo.Raven -v", the command returns  "Error Code: 7".  Here's the full output:

[francis@fedora src]$ ./Raven.exe -v
3.8.0 w/ netCDF
============== Early Gracefully Exit ==============
Error Statement: Version check
Error Code: 7
---------------------------------------------------

### Steps To Reproduce

1. Compile Raven v3.8
2. Use the command "./Raven.exe -v"
3. Return Error Code: 7 instead of the version number

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

**Comment by mdunphy** [comment] 2024-05-01 02:44
Error Code 7 corresponds to "SIMULATION_DONE", so this amounts to a graceful exit after printing the version -- looks like not a bug

**Comment by Zeitsperre** [comment] 2024-05-03 20:48
Can confirm, it looks as though this intentional.

**Comment by analytophile** [comment] 2024-05-29 19:28
resolved in update on May 28, 2024

**Closed by analytophile** 2024-05-29 19:28 UTC
Labels: bug
